services:
  jg_nav:
    image: jg_nav:latest
    build: .
    container_name: jg_nav
    ports:
      - "2266:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - jg_data:/app/data
      - jg_uploads:/app/public/uploads
    restart: unless-stopped

volumes:
  jg_data:
  jg_uploads:
